`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// National University of Singapore
// Department of Electrical and Computer Engineering
// EE2026 Digital Design
// AY1819 Semester 1
// Project: Voice Scope
//////////////////////////////////////////////////////////////////////////////////

module Voice_Scope_TOP(
    input CLK,
    
    input  J_MIC3_Pin3,   // PmodMIC3 audio input data (serial)
    output J_MIC3_Pin1,   // PmodMIC3 chip select, 20kHz sampling clock
    output J_MIC3_Pin4,   // PmodMIC3 serial clock (generated by module VoiceCapturer.v)
    
    output J_DA2_Pin1,    // PmodDA2 sampling clock (generated by module DA2RefComp.vhd)
    output J_DA2_Pin2,    // PmodDA2 Data_A, 12-bit speaker output (generated by module DA2RefComp.vhd)
    output J_DA2_Pin3,    // PmodDA2 Data_B, not used (generated by module DA2RefComp.vhd)
    output J_DA2_Pin4,    // PmodDA2 serial clock, 50MHz clock
    
    output [3:0] VGA_RED,    // RGB outputs to VGA connector (4 bits per channel gives 4096 possible colors)
    output [3:0] VGA_GREEN,
    output [3:0] VGA_BLUE,
    
    output VGA_VS,          // horizontal & vertical sync outputs to VGA connector
    output VGA_HS
    );
    
    
// Please create a clock divider module to generate 20kHz and 10Hz clock signals. 
// Instantiate it below
    wire clk_20k;
    wire clk_10Hz;
    
    clk_div (CLK, 2499, clk_20k); 
    clk_div (CLK, 4999999, clk_10Hz); 
    
    VOICE_CAPTURER capturer (CLK, clk_20k, 
// Please instantiate the voice capturer module below
    wire [11:0] MIC_in;
    
// Please instantiate the waveform drawer module below
    wire [11:0] VGA_HORZ_COORD;
    wire [11:0] VGA_VERT_COORD; 
    
    wire [3:0] R_wave;
    wire [3:0] G_wave;
    wire [3:0] B_wave;
    
    wire clk_sample;
    wire clk_display;
    wire [9:0] wave_sample;
    
    TestWave_gen testwave_gen (clk_20k, wave_sample); 
    
// Please instantiate the background drawing module below   
    wire [3:0] R_grid;
    wire [3:0] G_grid;
    wire [3:0] B_grid;
    
    
// Please instantiate the VGA display module below     
    
                    
                    
endmodule
